---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
hdfs:
  #superuser for hdfs
  superuser: ${hdfs.user:hdfs}
  #path on hdfs where broker creates dirs for user apps
  userspace.chroot: ${broker.userspace.path:/org/%{organization}/brokers/userspace/%{instance}}
  #path on container where keytab for hdfs is
  keytab.path: ${hdfs.keytab.path:}
  #path on container where configuration for hdfs is
  configuration.path: ${hdfs.configuration.path:}
#optional parameters to configure zookeeper-store
store:
  path: ${broker.store.znode:/broker/hdfs}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:hdfs}
    serviceId: ${cf.catalog.serviceid:hdfs}
    serviceDescription: HDFS service for creating directories on hadoop distributed file system.
    baseId: ${BASE_GUID:}
    plans:
      - id: plain-dir-plan
        name: plain-dir
        description: Create directory on HDFS within storage space shared across your organization.
        free: true
      - id: encrypted-dir-plan
        name: encrypted-dir
        description: Create encrypted directory on HDFS within storage space shared across your organization.
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}
