---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
hdfs:
  #superuser for hdfs
  superuser: ${hdfs.user:hdfs}
  #path on hdfs where broker creates dirs for user apps
  userspace.chroot: ${broker.userspace.path:/org/%{organization}/brokers/userspace/%{instance}}
  #path on container where keytab for hdfs is
  keytab.path: ${hdfs.keytab.path:}
  #path on container where configuration for hdfs is
  configuration.path: ${hdfs.configuration.path:}
#parameters for communication between hdfs-broker and hadoop groups mapping server
group.mapping:
  url: ${hgm.url}
  kerberos:
    principal: ${hgm.principal:}
    keytab.path: ${hgm.keytab.path:}
  https:
    username: ${hgm.username:}
    password: ${hgm.password:}
#parameters for communication between hdfs-broker and uaa
uaa:
  tokenUri: ${vcap.services.sso.credentials.tokenUri}
  uri: ${vcap.services.sso.credentials.uaaUri}
  clientId: ${vcap.services.sso.credentials.clientId}
  clientSecret: ${vcap.services.sso.credentials.clientSecret}
#optional parameters to configure zookeeper-store
store:
  path: ${broker.store.znode:/broker/hdfs}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:hdfs}
    serviceId: ${cf.catalog.serviceid:hdfs}
    serviceDescription: HDFS service for creating directories on hadoop distributed file system.
    baseId: ${BASE_GUID:}
    plans:
      - id: create-user-directory-plan
        name: create-user-directory
        description: This plan creates directory along with technical user who has only permissions for that directory (with HDFS configuration).
        free: true
      - id: get-user-directory-plan
        name: get-user-directory
        description: This plan based on instance created in plan create-user-direcotry (requires parameter uri from this instance). It's able to return credentials and directory (with HDFS configuration).
        free: true
      - id: shared-plan
        name: shared
        description: This plan creates directory on hdfs where all users from organization have sufficient permissions (with HDFS configuration).
        free: true
      - id: encrypted-plan
        name: encrypted
        description: This plan creates directory with encryption zones, which allow for encryption at-rest on HDFS (with HDFS configuration).
        free: true
      - id: multitenant-plan
        name: multitenant
        description: This plan provides template for multitenant TAP applications.
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}
